<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);

return array(
    'Twig_' => $vendorDir . '/twig/twig/lib/',
    'Symfony\\Component\\Yaml' => $vendorDir . '/symfony/yaml/',
    'Symfony\\Component\\DependencyInjection' => $vendorDir . '/symfony/dependency-injection/',
    'Symfony\\Component\\ClassLoader' => $vendorDir . '/symfony/class-loader/',
    'Symfony' => $vendorDir . '/symfony/symfony/src/',
    'Monolog' => $vendorDir . '/monolog/monolog/src/',
    'Framework' => dirname(dirname(dirname($vendorDir))) . '/src/',
    'Doctrine\\Common' => $vendorDir . '/doctrine/common/lib/',
);
